application:
  domain: xx.com
  services:
    api:
      port: 9907
    admin:
      port: 9908
  password_token: "&^*!#@(*YC&(OJ@BDS(ASDHDD"
  jwt_token: "&^*!#@(*YC&(OJ@BDS(ASDHEE"

database:
  master:
    addr: mysql:3306
    username: root
    password: 123456
    dbname: word
    max_idle: 100
    max_open: 200
  slave:
    - addr: mysql:3306
      username: root
      password: 123456
      dbname: word
      max_idle: 100
      max_open: 200

mongo:
  url: "mongodb://mongo:27017"
  database: "word"
  # 保持空闲的最大时间,单位: 秒
  max_conn_idle_time: 180
  # 连接池大小,设置为机器能承受的最大值
  max_pool_size: 2000
  username: "admin"
  password: "123456"

captcha:
  addr: "redis:6379"
  password: ""
  db: 0
  pool_size: 2000
  min_idle_conns: 2000

email:
  username: xxx@xxx.com
  password: xxx
  host: smtp.xxx.com
  ssl: true
  port: 465

redis:
  addr: redis:6379
  password: ""
  db: 1
  pool_size: 1000
  min_idle_conns: 100

sessions:
  key: word
  name: word
  domain: word.com
  addr: redis:6379
  password:
  db: 5
  pool_size: 1000
  min_idle_conns: 500

sms:
  api_key: ""
  sms_api: ""
  user: ""
  password: ""

idauth:
  app_code:

log:
  path: /app/logs/